version: '3'
tasks:
  help:
    desc: Show available tasks
    cmds:
      - echo "Available tasks:"
      - echo ""
      - echo "  === Local Development (Kind) ==="
      - echo "  task kind-up               - Create Kind cluster and deploy app"
      - echo "  task kind-down             - Delete Kind cluster and cleanup"
      - echo "  task kind-status           - Check Kind deployment status"
      - echo "  task kind-logs             - View pod logs in Kind"
      - echo "  task kind-migrate          - Run database migrations"
      - echo "  task kind-seed             - Load sample data"
      - echo ""
      - echo "  === Azure Deployment ==="
      - echo "  task login                 - Login to Azure"
      - echo "  task azure-up              - Deploy to Azure AKS (full)"
      - echo "  task azure-down            - Destroy Azure resources"
      - echo "  task azure-status          - Check Azure deployment status"
      - echo ""
      - echo "  === Validation ==="
      - echo "  task validate-local        - Validate local Terraform config"
      - echo "  task validate-azure        - Validate Azure Terraform config"
      - echo ""
      - echo "  task clean                 - Remove local state files"

  # ---------------------------------------------------------------------------
  # Kind (local Kubernetes cluster)
  # ---------------------------------------------------------------------------

  kind-up:
    desc: Create Kind cluster and deploy app using Terraform
    cmds:
      - echo "Creating Kind cluster..."
      - kind create cluster --config kind-config.yaml --wait 60s
      - echo ""
      - echo "Deploying app with Terraform (local config)..."
      - cd terraform/local && terraform init
      - cd terraform/local && terraform apply -auto-approve
      - echo ""
      - echo "Waiting for pods to be ready..."
      - kubectl wait --for=condition=ready pod -l app=postgres -n train-routing --timeout=120s
      - kubectl wait --for=condition=ready pod -l app=backend -n train-routing --timeout=300s
      - kubectl wait --for=condition=ready pod -l app=frontend -n train-routing --timeout=180s
      - echo ""
      - echo "[OK] Deployment complete!"
      - cd terraform/local && terraform output
      - echo ""
      - echo "Access the app at http://localhost:30000"
      - echo "Run 'task kind-status' to check pods"

  kind-down:
    desc: Delete Kind cluster and cleanup Terraform
    cmds:
      - cd terraform/local && terraform destroy -auto-approve || true
      - kind delete cluster --name aks-local
      - echo "[OK] Kind cluster deleted"

  kind-status:
    desc: Check Kind deployment status
    cmds:
      - echo "=== Nodes ==="
      - kubectl get nodes
      - echo ""
      - echo "=== Pods ==="
      - kubectl get pods -n train-routing
      - echo ""
      - echo "=== Services ==="
      - kubectl get svc -n train-routing

  kind-logs:
    desc: View pod logs in Kind
    cmds:
      - echo "=== Backend Logs ==="
      - kubectl logs -n train-routing -l app=backend --tail=50
      - echo ""
      - echo "=== Frontend Logs ==="
      - kubectl logs -n train-routing -l app=frontend --tail=20

  kind-migrate:
    desc: Run database migrations
    cmds:
      - kubectl exec -n train-routing -it $(kubectl get pod -n train-routing -l app=backend -o jsonpath='{.items[0].metadata.name}') -- php bin/console doctrine:migrations:migrate --no-interaction

  kind-seed:
    desc: Load sample data (fixtures)
    cmds:
      - kubectl exec -n train-routing -it $(kubectl get pod -n train-routing -l app=backend -o jsonpath='{.items[0].metadata.name}') -- php bin/console doctrine:fixtures:load --no-interaction

  validate-local:
    desc: Validate local Terraform syntax
    dir: terraform/local
    cmds:
      - terraform init -backend=false
      - terraform validate
      - echo "[OK] Local Terraform configuration is valid"

  validate-azure:
    desc: Validate Azure Terraform syntax
    dir: terraform/azure
    cmds:
      - terraform init -backend=false
      - terraform validate
      - echo "[OK] Azure Terraform configuration is valid"

  # ---------------------------------------------------------------------------
  # Azure Deployment
  # ---------------------------------------------------------------------------

  login:
    desc: Login to Azure
    cmds:
      - az login
      - az account show

  azure-up:
    desc: Deploy to Azure AKS (creates cluster + deploys app)
    cmds:
      - echo "Deploying to Azure..."
      - cd terraform/azure && terraform init
      - cd terraform/azure && TF_VAR_subscription_id=$(az account show --query id -o tsv) terraform apply
      - echo ""
      - echo "[OK] Azure deployment complete!"
      - cd terraform/azure && terraform output

  azure-down:
    desc: Destroy all Azure resources
    cmds:
      - cd terraform/azure && TF_VAR_subscription_id=$(az account show --query id -o tsv) terraform destroy
      - rm -rf terraform/azure/.terraform terraform/azure/terraform.tfstate* terraform/azure/.terraform.lock.hcl
      - echo "[OK] Azure resources destroyed and state cleaned"

  azure-plan:
    desc: Plan Azure infrastructure changes
    dir: terraform/azure
    cmds:
      - terraform init
      - TF_VAR_subscription_id=$(az account show --query id -o tsv) terraform plan

  azure-status:
    desc: Check Azure deployment status
    cmds:
      - az aks get-credentials --resource-group aks-poc-rg --name aks-poc-cluster --overwrite-existing
      - echo "=== Nodes ==="
      - kubectl get nodes
      - echo ""
      - echo "=== Pods ==="
      - kubectl get pods -n train-routing
      - echo ""
      - echo "=== Services ==="
      - kubectl get svc -n train-routing
      - echo ""
      - echo "=== Frontend URL ==="
      - kubectl get svc frontend -n train-routing -o jsonpath='http://{.status.loadBalancer.ingress[0].ip}'
      - echo ""

  clean:
    desc: Remove all Terraform state files
    cmds:
      - rm -rf terraform/local/.terraform terraform/local/terraform.tfstate* terraform/local/.terraform.lock.hcl
      - rm -rf terraform/azure/.terraform terraform/azure/terraform.tfstate* terraform/azure/.terraform.lock.hcl
      - echo "[OK] Cleaned up Terraform state files"
